import os


class Config:
    RI_API_BASE_URL = os.getenv("RI_API_BASE_URL", "")
    RI_API_TEST_CLIENT_ID = os.getenv("RI_API_TEST_CLIENT_ID", "")
    RI_API_TEST_CLIENT_SECRET = os.getenv("RI_API_TEST_CLIENT_SECRET", "")

    RI_AUTH_ENDPOINT = os.getenv("RI_AUTH_ENDPOINT", "")
    RI_AUTH_REFRESH_ENDPOINT = os.getenv("RI_AUTH_REFRESH_ENDPOINT", "")

    RI_TEST_CLIENT_ID = os.getenv("RI_TEST_CLIENT_ID", "")
    RI_TEST_CLIENT_SECRET = os.getenv("RI_TEST_CLIENT_SECRET", "")

    RI_VERIFY_ACCOUNT_ROUTING_V1_ENDPOINT = os.getenv(
        "RI_VERIFY_ACCOUNT_ROUTING_V1_ENDPOINT", ""
    )
    RI_VERIFY_ACCOUNT_ROUTING_V2_ENDPOINT = os.getenv(
        "RI_VERIFY_ACCOUNT_ROUTING_V2_ENDPOINT", ""
    )
